### ISSUE TITLE
我认为minidb，merge有个小问题

### ISSUE THREAD

**Issue by mabiao0525** [rosedblabs/mini-bitcask#22]
在merge中，当有效Entry队列大于0时才进行更新，但是这是由BUG的，就如样例所示，增加后又删除，此时文件里内容应该为空，所以应该把db.go中75行更改为 if len(validEntries) >= 0

**Comment by roseduan** [comment]
能给个 example code 吗
也欢迎 PR

**Comment by mabiao0525** [comment]
就是当前版本的example就有问题，执行删除操作后，再执行Merge操作，我认为应该数据文件变为空的，但是打开底层真实文件后，发现里面不为空，还是存在示例数据。
